import_from_git(
  url: "https://github.com/starburst997/apple-code-sign.git",
  branch: "v1",
  path: "fastlane/iOS/Fastfile"
)

import_from_git(
  url: "https://github.com/starburst997/apple-code-sign.git",
  branch: "v1",
  path: "fastlane/macOS/Fastfile"
)