name: Build iOS

on: 
  #push
  #pull_request
  workflow_dispatch:

jobs:
  build:
    uses: starburst997/apple-code-sign/.github/workflows/ios.yml@v1
    secrets: inherit
    with:
      project_path: iOS
      xcodeproj_path: Test.xcodeproj
      plist_path: Test/Info.plist
      project_target: Test
      version: "2025.1"
      artifact: true