name: Build MacOS

on: 
  #push
  #pull_request
  workflow_dispatch:

jobs:
  build:
    uses: starburst997/apple-code-sign/.github/workflows/macos.yml@v1
    secrets: inherit
    with:
      project_path: macOS
      xcodeproj_path: Test.xcodeproj
      plist_path: Test/Info.plist
      project_target: Test
      version: "2025.1"
      artifact: true
      generate_appstore: true
      generate_developer_id: true
      generate_dmg: true